<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 0;
        }
        .header {
            background-color: #1e3a8a;
            color: white;
            padding: 30px;
            text-align: center;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            text-transform: uppercase;
            letter-spacing: 2px;
        }
        .header p {
            margin: 5px 0 0;
            opacity: 0.8;
            font-size: 14px;
        }
        .content {
            padding: 40px;
        }
        .meta {
            margin-bottom: 30px;
            padding-bottom: 10px;
            border-bottom: 2px solid #eee;
            display: flex;
            justify-content: space-between;
        }
        .meta-item {
            font-size: 12px;
            color: #666;
        }
        .section-title {
            color: #1e3a8a;
            font-size: 18px;
            margin-top: 30px;
            margin-bottom: 15px;
            border-left: 4px solid #1e3a8a;
            padding-left: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table th, table td {
            text-align: left;
            padding: 12px;
            border-bottom: 1px solid #eee;
            font-size: 13px;
        }
        table th {
            background-color: #f8fafc;
            color: #64748b;
            text-transform: uppercase;
            font-size: 11px;
            letter-spacing: 1px;
        }
        .stats-grid {
            display: flex;
            flex-wrap: wrap;
            margin: -10px;
        }
        .stat-card {
            flex: 1;
            min-width: 150px;
            background: #f8fafc;
            padding: 20px;
            margin: 10px;
            border-radius: 8px;
            text-align: center;
        }
        .stat-value {
            font-size: 24px;
            font-weight: bold;
            color: #1e3a8a;
            display: block;
        }
        .stat-label {
            font-size: 11px;
            color: #64748b;
            text-transform: uppercase;
            margin-top: 5px;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            padding: 20px;
            text-align: center;
            font-size: 10px;
            color: #94a3b8;
            border-top: 1px solid #eee;
        }
        .status-badge {
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: bold;
            text-transform: uppercase;
        }
        .status-approved { background-color: #dcfce7; color: #166534; }
        .status-pending { background-color: #fef9c3; color: #854d0e; }
        .status-rejected { background-color: #fee2e2; color: #991b1b; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Manarah Port Authority</h1>
        <p>Executive Analytics & Reporting System</p>
    </div>

    <div class="content">
        <div class="meta">
            <div class="meta-item">
                <strong>Report Type:</strong> {{ $reportType }}
            </div>
            <div class="meta-item">
                <strong>Generated:</strong> {{ now()->format('Y-m-d H:i') }}
            </div>
            <div class="meta-item">
                <strong>Date Range:</strong> {{ $startDate }} to {{ $endDate }}
            </div>
        </div>

        @yield('content')
    </div>

    <div class="footer">
        &copy; {{ date('Y') }} Manarah Port Authority. Confidential Executive Report. Generated by {{ auth()->user()->name ?? 'System' }}.
    </div>
</body>
</html>
